- name: Include vars from kafka
  include_vars:
    file: ../vars/vault.yml

- name: kafka installation
  block:
    - name: create kafka user
      user:
        name: kafka
        home: /home/kafka
        shell: /bin/bash
        password: "{{ kafka_user_pass | password_hash('sha256') }}"
      
    - name: lock kafka user
      user:
        name: kafka
        password_lock: yes

    - name: create Downloads directory
      file:
        path: /home/kafka/Downloads
        owner: kafka
        group: kafka
        state: directory
    
    - name: download kafka
      get_url:
        url: https://www.apache.org/dist/kafka/2.1.1/kafka_2.11-2.1.1.tgz
        owner: kafka
        group: kafka
        dest: /home/kafka/Downloads/kafka.tgz
      register: kafa_result
      retries: 5
      delay: 5
      until: kafa_result is succeeded
    
    - name: extract kafka files
      unarchive:
        src: /home/kafka/Downloads/kafka.tgz
        owner: kafka
        group: kafka
        dest: /home/kafka/
        remote_src: yes

    - name: enable topic deletion on kafka
      lineinfile:
        path: /home/kafka/kafka_2.11-2.1.1/config/server.properties
        line: "delete.topic.enable = true"
        insertafter: EOF
    
    - name: replace listeners url on kafka
      lineinfile:
        path: /home/kafka/kafka_2.11-2.1.1/config/server.properties
        regexp: '^listeners=PLAINTEXT://:9092'
        insertafter: '^#listeners=PLAINTEXT://:9092'
        line: 'listeners=PLAINTEXT://{{ ansible_enp0s3.ipv4.address }}:9092'
    
    - name: replace advertised url on kafka
      lineinfile:
        path: /home/kafka/kafka_2.11-2.1.1/config/server.properties
        regexp: '^advertised.listeners=PLAINTEXT://your.host.name:9092'
        insertafter: '^#advertised.listeners=PLAINTEXT://your.host.name:9092'
        line: 'advertised.listeners=PLAINTEXT://{{ ansible_enp0s3.ipv4.address }}:9092'
    
    - name: create systemd service files
      include_tasks: create_service.yml
      loop:
        - kafka
        - zookeeper
      loop_control:
        loop_var: service_name

    - name: add firewall rule file for kafka
      copy:
        src: kafka.xml
        dest: /etc/firewalld/services/
        
    - name: Reload firewalld service
      service:
        name: firewalld
        state: reloaded

    - name: add kafka firewall exception
      firewalld:
        service: kafka
        permanent: yes
        state: enabled

    - name: add firewall rule exception for port 9092
      firewalld:
        port: 9092/tcp
        permanent: yes
        state: enabled
    
    - name: Reload firewalld service
      service:
        name: firewalld
        state: reloaded
    
    - name: start kafka service
      service:
        name: kafka
        state: started


