- name: Include vars from kafka
  include_vars:
    file: ../vars/vault.yml

- name: kafka installation
  block:
    - name: create kafka user
      user:
        name: kafka
        home: /home/kafka
        shell: /bin/bash
        password: "{{ kafka_user_pass }}"
    
    - name: create Downloads directory
      file:
        path: /home/kafka/Downloads
        owner: kafka
        group: kafka
        state: directory
    
    - name: download kafka
      get_url:
        url: https://www.apache.org/dist/kafka/2.1.1/kafka_2.11-2.1.1.tgz
        owner: kafka
        group: kafka
        dest: /home/kafka/Downloads/kafka.tgz
        
    - name: extract kafka files
      unarchive:
        src: /home/kafka/Downloads/kafka.tgz
        owner: kafka
        group: kafka
        dest: /home/kafka

