- name: jenkins installation
  block:
    - name: add jenkins repo
      yum_repository:
        name: jenkins
        description: Jenkins-stable
        baseurl: http://pkg.jenkins-ci.org/redhat-stable
        gpgcheck: yes

    - name: import jenkins rpm key
      rpm_key:
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    
    - name: install jenkins
      yum:
        name: jenkins
        state: latest