- name: jenkins installation
  block:
    - name: add jenkins repo
      yum_repository:
        name: jenkins
        description: Jenkins-stable
        baseurl: http://pkg.jenkins-ci.org/redhat-stable
        gpgcheck: yes

    - name: import jenkins rpm key
      rpm_key:
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    
    - name: install jenkins
      yum:
        name: jenkins
        state: latest
    
    - name: add firewall rule exception for jenkins
      firewalld:
        service: jenkins
        permanent: yes
        state: enabled
    
    - name: add firewall rule exception for port 8080
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
    
    - name: Reload firewalld service
      service:
        name: firewalld
        state: reloaded
    
    - name: Restart Jenkins service
      service:
        name: jenkins
        state: restarted
  