- name: common packages installation
  block:
    - name: yum update
      yum:
        name: '*'
        state: latest
    
    - name: install needed applications
      yum:
        name: "{{ application }}"
        state: latest
      loop:
        - java-1.8.0-openjdk
        - net-tools
        - vim
        - git
        - maven
      loop_control:
        loop_var: application