pipeline {
    
    agent any
    
    stages{
        stage('Checkout SCM code') {
            steps {
                //echo 'Code checked out'
                git(
                    url: 'https://github.com/EduardoZimelewicz/spring-boot-with-kafka.git',
                    credentialsId: 'github',
                    branch: 'master')
                sh "ls -la"
            }
        }
        
        stage('Maven build') {
            steps {
                //echo 'Mvn Build'
                sh "mvn clean package"
            }
        }
        
        stage('Deploy code') {
            steps {
                sh "sudo mkdir -p /var/spring-boot-with-kafka"
                sh "sudo cp target/spring-boot-with-kafka-0.0.1-SNAPSHOT.jar /var/spring-boot-with-kafka/"
                sh "sudo chown bootapp:bootapp /var/spring-boot-with-kafka/spring-boot-with-kafka-0.0.1-SNAPSHOT.jar"
                sh "sudo ln -sfn /var/spring-boot-with-kafka/spring-boot-with-kafka-0.0.1-SNAPSHOT.jar /etc/init.d/spring-boot-with-kafka"
                sh "sudo service spring-boot-with-kafka start"            
            }
        }
    }
}